### ISSUE TITLE
Great work!!! Enhancement request   

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentralAssistant#1]
I downloaded, compiled and tested with latest 0.6.62 MC server version.
Amazing idea!!!!!
Also tested it and really like the "?" mark on the list with computers :)
Can this be added to MeshAgent as an option, also controlled from MC server, let's say on device to have an option for MeshAssistant to start automatically with MeshAgent or not.
Possibly will be more ideas, but at the moment optional start with MeshAgent is the main :)
THANKS again!!!!

**Comment by Ylianst** [comment]
Not sure what the request is. Currently no way to auto-install the MeshCentral Assistant from the agent, is that the request?

**Comment by vitko-bg** [comment]
Actually the request is - on Meshcentral to have an option for certain groups to install and start Mesh Assistant when agent starts.
Not sure if that is easy to implement, but I think that it will be very useful.
Thanks.

**Comment by vitko-bg** [comment]
> Not sure what the request is. Currently no way to auto-install the MeshCentral Assistant from the agent, is that the request?

Yes :)
