### ISSUE TITLE
Unable to download or edit files

### ISSUE THREAD

**Issue by ramiresviana** [Ylianst/MeshCentralAssistant#15]
Using MeshCentral file explorer to download or edit files is not possible with MeshCentralAssistant, it shows an empty modal for the editor and no feedback when trying to download a file.

**Comment by Ylianst** [comment]
Just fixed this. Will requires an updated MeshCentral Assistant that will be in MeshCentral v0.9.16.

**Comment by ramiresviana** [comment]
File editing and download is now working properly since v0.9.16.

**Comment by mas1701** [comment]
> Just fixed this. Will requires an updated MeshCentral Assistant that will be in MeshCentral v0.9.16.

Did you break this again!? I'm having the OP's problem, but I'm on MeshCentral 1.1.10.

What I do:
During a MeshAssistant session, I click on Files and then on Connect. Other side approves. Getting an empty list. No drives, path or files to choose from.
