### ISSUE TITLE
Open Site ... Opens an agent port link, not the site itself ....

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentralAssistant#2]
When click on "Open SIte ..." it opens URL remote.domain.com:449 and cannot get to it.
Actually port 449 is only for my agents to connect.
Probably another line in MeshAgent.msh have to be added to point to real URL or other server configurable URL, so MeshAssintant can get the option from there.

**Comment by Ylianst** [comment]
Ha right. Your right, if you have the agent port set, it will not use the right port. I need to fix this.

**Comment by Ylianst** [comment]
Ok, I removed that link completely in MeshCentral v0.7.4. The link was derived from there the agent connects which it not always correct. It's also unclear if users should have access to the server link, so probably best to remove it.

**Comment by vitko-bg** [comment]
Thanks! That should work. Once tested will report back.
