### ISSUE TITLE
On "Request Help" no way to close this request form MC upon completion

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentralAssistant#3]
In case if help is provided already to requested computer, how to close that request from MC server side?
Employees won't remember to click again on the MeshAssistant and to cancel the request, once help is provided.
Thanks.

**Comment by Ylianst** [comment]
No way to close it on the server side yet, but need to add that.

**Comment by vitko-bg** [comment]
That would be great. Thanks.

**Comment by Ylianst** [comment]
Added a way to dismiss the help request in MeshCentral v0.7.4. Let me know if it works.

![MC2-AssistantDismissHelp](https://user-images.githubusercontent.com/1319013/100494617-13f86280-30f8-11eb-9c40-14a7b0bcd5dd.png)

**Comment by vitko-bg** [comment]
Thanks! Will update all EXEs and MC2 and will report back.

**Comment by Ylianst** [comment]
With latest versions of MeshCentral Assistant, once you update the server it should auto-update the MeshCentral Assistant. So, try it out and see if it needs an update at all.

**Comment by vitko-bg** [comment]
Hi @Ylianst  - I updated MC2 server, you are right - a new option to dismiss remote help appeared. However, when trying to Dismiss the notification - nothing happends.
The next step I have done - downloaded e MC Assistant source and started making changes (as no customization available) to Build the EXE for me. Changes I do are:
MainForm.cs -> MainForm.Designer.cs
this.mainNotifyIcon.BalloonTipTitle = "Assistant";
this.mainNotifyIcon.Text = "Assistant";
this.Text = "Assistant";

However - cannot build my own EXE, as on first start it is updating itself somehow?!?!? It is creating .update.exe file and deleting my customized EXE.

Please advise how I can comment this:
  //
        // Self update section
        //

        string seflUpdateDownloadHash = null;
        string serverTlsCertHash = null;

**Comment by vitko-bg** [comment]
In regards to the above comment, in short I am looking for MC Assistant customization :)
To be able to customize "MeshCentral Assistant" on windows title to "MyCompany Assistant".
Thanks.
