### ISSUE TITLE
Feature request: include assistent with agent

### ISSUE THREAD

**Issue by hunter-nl** [Ylianst/MeshCentralAssistant#7]
Include assistent with the agent installer and start the assistent when configured for configured device group(s).

**Comment by vitko-bg** [comment]
Looks like similar to #1 Not sure if @Ylianst will implement this soon.

**Comment by Ylianst** [comment]
So, I put in agent code in MeshCentral Assistant. I also started work on getting Assistant installed from the agent, but never finished that. So much to do!

![MC2-Assistant1](https://user-images.githubusercontent.com/1319013/118862045-0e532c80-b892-11eb-8d54-e6d3081d9731.png)
